language: go
services:
  - docker
go:
  - 1.11.5
install: 
  - echo "remove default travis_install to avoid getting workspace dirty with go dependency"
script:
  - make test-unit
  - .travis/check_workspace.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./docker_push.sh && ./docker_push.sh
  on:
    branch: master